spring:
  data:
    mongodb:
      database: wishlistdb
      auto-index-creation: true
      uri: "mongodb://localhost:27017/wishlist?serverSelectionTimeoutMS=1000&connectTimeoutMS=1000"
server:
  port: 8080